### ISSUE TITLE
Great work!

### ISSUE THREAD

**Issue by FGRibreau** [jenkins-contrib-themes/jenkins-neo-theme#10]
Great work! Just wanted to let you know [that we set it up](https://twitter.com/FGRibreau/status/697490254891188224) and it's beautiful!

<img width="1271" alt="capture d ecran 2016-02-10 19 38 42" src="https://cloud.githubusercontent.com/assets/138050/12957829/0543653e-d02f-11e5-8d9a-165b20f77887.png">

**Comment by aarjithn** [comment]
Thanks a lot for sharing your setup. Indeed looks beautiful. It is a pleasure knowing your effort benefits somebody :)
