### ISSUE TITLE
Center enable button

### ISSUE THREAD

**Issue by raderio** [jenkins-contrib-themes/jenkins-neo-theme#4]
Center enable job button

![enable_button](https://cloud.githubusercontent.com/assets/4563564/12943400/b06d4e02-cfe9-11e5-940f-653f85007363.png)

Chrome Version 44.0.2403.89

**Comment by aarjithn** [comment]
This is fixed now!

<img width="478" alt="screen shot 2016-02-21 at 00 34 20" src="https://cloud.githubusercontent.com/assets/10304259/13200118/f0f0c110-d832-11e5-9291-45f31a8c0adc.png">
