### ISSUE TITLE
Disabled and Not Build icons do not exist

### ISSUE THREAD

**Issue by RockyMM** [jenkins-contrib-themes/jenkins-neo-theme#6]
![image](https://cloud.githubusercontent.com/assets/1906065/12945055/5726fdd2-cfeb-11e5-95de-68f503cbcc64.png)

**Comment by afonsof** [comment]
This bug was already fixed in jenkins-material-theme: https://github.com/afonsof/jenkins-material-theme/issues/24.
We can use the same code to fix it here.

**Comment by RockyMM** [comment]
That would be awesome. I cannot find commit relating to afonsof/jenkins-material-theme#24, but I'll try.

**Comment by RockyMM** [comment]
Found it! https://github.com/afonsof/jenkins-material-theme/commit/592ec5e1ee0d8a3ae046d9c0897107ecdeebc3cd

**Comment by afonsof** [comment]
@RockyMM https://github.com/afonsof/jenkins-material-theme/commit/2a3d9ee75a627778841808c22127a2ea08ff5f26

**Comment by RockyMM** [comment]
@afonsof although, I would be more happy if different icons were used, but it's better some icons than no icons :)

**Comment by RockyMM** [comment]
Hey @afonsof I'm quite novice with GitHub workflow, don't hold grudge against me if I did something wrong ;)

**Comment by afonsof** [comment]
@RockyMM we've discussed about different icons in the other repo. You are right maybe different icons should be be a better solution. I decided to use the same icon because jenkins uses the same icon and it's hard to find good Material Design icons that express different meanings. Anyway I guess we can improve it :smile:

**Comment by RockyMM** [comment]
@afonsof Yep, just right now is not the best time. Anyways, I completely forgot about disabled icon. I feel a bit challenged creating these PRs :laughing:

**Comment by RockyMM** [comment]
Now that the PR is merged should we close it?

**Comment by aarjithn** [comment]
I've merged the pull request as of now. I see the icons has been fixed by @afonsof. We are thinking to merge our code bases, so issues like this can be better addressed rather than being duplicated across both repos.
